//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoomanLogic.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public Action()
        {
            this.RecurrenceRules = new HashSet<RecurrenceRule>();
            this.ChildPathways = new HashSet<ActionPathway>();
            this.ParentPathways = new HashSet<ActionPathway>();
            this.RootPathways = new HashSet<ActionPathway>();
            this.Tags = new HashSet<Tag>();
        }
    
        public System.Guid Id { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Kind { get; set; }
        public Nullable<System.DateTime> Enlist { get; set; }
        public Nullable<System.DateTime> Retire { get; set; }
        public Nullable<short> StartAt { get; set; }
        public Nullable<short> Duration { get; set; }
        public Nullable<System.DateTime> NextDate { get; set; }
        public bool IsSomeday { get; set; }
        public string Content { get; set; }
        public bool IsPublic { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<RecurrenceRule> RecurrenceRules { get; set; }
        public virtual ICollection<ActionPathway> ChildPathways { get; set; }
        public virtual ICollection<ActionPathway> ParentPathways { get; set; }
        public virtual ICollection<ActionPathway> RootPathways { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
