//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoomanLogic.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionPathway
    {
        public System.Guid RootId { get; set; }
        public System.Guid ParentId { get; set; }
        public System.Guid ChildId { get; set; }
        public Nullable<byte> Order { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Action Action1 { get; set; }
        public virtual Action Action2 { get; set; }
    }
}
