//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoomanLogic.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public string UserId { get; set; }
        public string Persona { get; set; }
        public string UserId_Connection { get; set; }
        public string Persona_Connection { get; set; }
    
        public virtual AspNetUser Me { get; set; }
        public virtual AspNetUser Them { get; set; }
        public virtual Persona MyPersona { get; set; }
        public virtual Persona TheirPersona { get; set; }
    }
}
