//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoomanLogic.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEntryPeanut
    {
        public System.Guid Id { get; set; }
        public string UserId { get; set; }
        public System.Guid LogEntryId { get; set; }
        public System.DateTime Date { get; set; }
        public string Kind { get; set; }
        public string Comment { get; set; }
        public string AttachmentUri { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual LogEntry LogEntry { get; set; }
    }
}
