//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoomanLogic.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.Guid Id { get; set; }
        public string UserId_From { get; set; }
        public string UserId_To { get; set; }
        public string Text { get; set; }
        public string Uri { get; set; }
        public System.DateTime Sent { get; set; }
        public Nullable<System.DateTime> Read { get; set; }
    
        public virtual AspNetUser Sender { get; set; }
        public virtual AspNetUser Receiver { get; set; }
    }
}
