//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoomanLogic.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public System.Guid Id { get; set; }
        public string UserId { get; set; }
        public System.DateTime OccurredAt { get; set; }
        public string Kind { get; set; }
        public string Subject { get; set; }
        public string Context { get; set; }
        public Nullable<System.DateTime> ReadAt { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
