//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoomanLogic.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Connections = new HashSet<Connection>();
            this.Connections1 = new HashSet<Connection>();
        }
    
        public string UserId { get; set; }
        public string Kind { get; set; }
        public string KnownAs { get; set; }
        public string ProfileUri { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Connection> Connections { get; set; }
        public virtual ICollection<Connection> Connections1 { get; set; }
    }
}
