//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoomanLogic.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStep
    {
        public ProjectStep()
        {
            this.Actions = new HashSet<Action>();
            this.Children = new HashSet<ProjectStep>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ProjectId { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Kind { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<short> Duration { get; set; }
        public string Status { get; set; }
        public string TagName { get; set; }
        public string Content { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<short> Ordinal { get; set; }
    
        public virtual ICollection<Action> Actions { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<ProjectStep> Children { get; set; }
        public virtual ProjectStep Parent { get; set; }
    }
}
