//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoomanLogic.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectSteps = new HashSet<ProjectStep>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid FocusId { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Kind { get; set; }
        public string TagName { get; set; }
        public Nullable<System.DateTime> Enlist { get; set; }
        public Nullable<System.DateTime> Retire { get; set; }
        public string IconUri { get; set; }
        public string Content { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Focus Focus { get; set; }
        public virtual ICollection<ProjectStep> ProjectSteps { get; set; }
    }
}
