//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoomanLogic.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurrenceRule
    {
        public System.Guid ActionId { get; set; }
        public string Rule { get; set; }
    
        public virtual Action Action { get; set; }
    }
}
