//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoomanLogic.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Actions = new HashSet<Action>();
            this.Targets = new HashSet<Target>();
        }
    
        public System.Guid Id { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Kind { get; set; }
        public string Path { get; set; }
        public bool IsFocus { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Action> Actions { get; set; }
        public virtual ICollection<Target> Targets { get; set; }
    }
}
