//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoomanLogic.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Target
    {
        public System.Guid Id { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string EntityType { get; set; }
        public Nullable<System.Guid> EntityId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Retire { get; set; }
        public byte Measure { get; set; }
        public short Number { get; set; }
        public System.DateTime Starts { get; set; }
        public byte Period { get; set; }
        public short Multiplier { get; set; }
        public bool RetireWhenMet { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
